degree:
	python plots/plot_degree.py /home/marvin/workspace/data/dbpedia-tkg/stats_1217_1613/FULL/yearlyOutDegreeDistribution/part-00000-b56c3516-e455-4cab-a302-a390601b825c-c000.csv degree_distribution.png

degree_obj:
	python plots/plot_degree.py /home/marvin/workspace/data/dbpedia-tkg/stats_1217_1613/FULL/yearlyOutDegreeDistributionOnlyObjects/part-00000-54bece74-d486-49b9-b13b-4c3de706a60b-c000.csv degree_obj_distribution.png
