from __future__ import annotations

from rdflib import Namespace

DBO = Namespace("http://dbpedia.org/ontology/")

SUBDOMAINS = [
    "People & biography",
    "Geography & places",
    "Organizations",
    "Creative works",
    "Events",
    "Science & medicine",
    "Technology & software",
    "Sports",
    "Politics & government",
    "Infrastructure & transport",
    "Biology",
]

ANCHORS_BY_DOMAIN: dict[str, set[str]] = {
    "People & biography": {"Person"},
    "Geography & places": {"Place"},
    "Organizations": {"Organisation"},
    "Creative works": {"Work"},
    "Events": {"Event"},
    "Science & medicine": {"Disease", "Drug", "MedicalSpecialty", "AnatomicalStructure"},
    "Technology & software": {"Software", "Device", "Technology"},
    "Sports": {"Athlete", "SportsTeam", "Sport", "SportsLeague"},
    "Politics & government": {"PoliticalParty", "Election", "GovernmentAgency", "Legislature"},
    "Infrastructure & transport": {
        "Infrastructure",
        "RouteOfTransportation",
        "TransportSystem",
        "Station",
    },
    "Biology": {"Species"},
}

SEMANTIC_KEYWORDS: dict[str, set[str]] = {
    "People & biography": {
        "person",
        "people",
        "actor",
        "artist",
        "athlete",
        "writer",
        "singer",
        "biography",
        "politician",
        "human",
    },
    "Geography & places": {
        "place",
        "city",
        "country",
        "river",
        "mountain",
        "region",
        "island",
        "lake",
        "valley",
        "location",
    },
    "Organizations": {
        "organisation",
        "organization",
        "company",
        "university",
        "institution",
        "agency",
        "team",
        "club",
        "society",
    },
    "Creative works": {
        "work",
        "film",
        "book",
        "album",
        "song",
        "television",
        "series",
        "novel",
        "artwork",
        "videogame",
        "video",
        "music",
        "magazine",
        "newspaper",
    },
    "Events": {
        "event",
        "festival",
        "battle",
        "election",
        "competition",
        "disaster",
        "ceremony",
        "conference",
        "tournament",
    },
    "Science & medicine": {
        "disease",
        "drug",
        "medical",
        "anatom",
        "scientific",
        "research",
        "chemical",
        "clinical",
        "biology",
        "health",
    },
    "Technology & software": {
        "software",
        "technology",
        "device",
        "computer",
        "programming",
        "algorithm",
        "application",
        "hardware",
        "engine",
        "internet",
    },
    "Sports": {
        "sport",
        "athlete",
        "team",
        "league",
        "coach",
        "stadium",
        "tournament",
        "race",
    },
    "Politics & government": {
        "politic",
        "government",
        "parliament",
        "legislature",
        "party",
        "election",
        "minister",
        "president",
        "senate",
    },
    "Infrastructure & transport": {
        "infrastructure",
        "transport",
        "station",
        "airport",
        "bridge",
        "road",
        "rail",
        "route",
        "highway",
        "port",
        "airline",
    },
    "Biology": {
        "species",
        "plant",
        "animal",
        "organism",
        "taxon",
        "genus",
        "family",
        "bacteria",
        "bird",
    },
}

DOMAIN_PRIORITY = {domain: i for i, domain in enumerate(SUBDOMAINS)}

